### PR TITLE
Post slack message when heroku deploy finishes with git details

### PR DESCRIPTION
**Pull request by eterry1388**
I really wanted to see more details about the PR/commit on the deploy messages in #rollbar. This is what I came up with:

Screen Shot 2020-07-17 at 3 37 22 PM

### CODE REVIEW

**Comment by eterry1388** [comment]
Didn't mean to make a PR in this repo. Closing

**Comment by evantahler** [comment]
But that's an awesome change!  Can you re-open this PR?

**Comment by evantahler** [comment]
... and I'm guessing `python3` exists in the default Heroku buildpack, even for node, ruby etc?

**Comment by evantahler** [comment]
I think this could be great generically, if you change the ENV to `GITHUB_OAUTH_TOKEN` and make the message conditional.  
If `GITHUB_OAUTH_TOKEN` is set, make the 'enhanced' message you've added, otherwise, make the message from only what we can get from Heroku

**Comment by evantahler** [comment]
closed by https://github.com/evantahler/heroku-buildpack-notify-slack-deploy/pull/2

**Comment by eterry1388** [comment]
Awesome! Thanks for running with this and implementing something that will work generically. We'll give it a go now!

**Pull request closed without merging**
